apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
    spec:
      serviceAccountName: monitoring-sa
      containers:
      - name: backend
        image: nginx:alpine
        ports:
        - containerPort: 8080
        command: ["/bin/sh"]
        args: ["apk add curl jq && while true; do echo '{\"pods\":$(kubectl get pods -n apps --no-headers 2>/dev/null|wc -l),\"services\":$(kubectl get svc -n apps --no-headers 2>/dev/null|wc -l),\"time\":\"$(date)\"}' > /usr/share/nginx/html/status.json; sleep 5; done & nginx -g daemon off;"]
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-backend
  ports:
  - port: 8080
    targetPort: 8080
