apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
    spec:
      serviceAccountName: monitoring-sa
      containers:
      - name: backend
        image: monitoring-backend:latest   # override with registry: kustomize edit set image monitoring-backend:latest=YOUR_REGISTRY/monitoring-backend:latest
        imagePullPolicy: Always   # always pull so rollout gets the image pushed by CI
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # Optional: send app logs to Kafka (Strimzi bootstrap in kafka namespace)
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: KAFKA_LOG_TOPIC
          value: "monitoring-logs"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-backend
  ports:
  - port: 8080
    targetPort: 8080
