apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
    spec:
      serviceAccountName: monitoring-sa
      containers:
      - name: backend
        image: nginx:alpine
        ports:
        - containerPort: 8080
        command: ["/bin/sh","-c"]
        args:
        - apk add --no-cache curl jq && while true; do POD_COUNT=$(kubectl get pods --no-headers -n apps 2>/dev/null|wc -l); SVC_COUNT=$(kubectl get svc --no-headers -n apps 2>/dev/null|wc -l); echo "{\"pods\":$POD_COUNT,\"services\":$SVC_COUNT,\"timestamp\":\"$(date)\"}" > /usr/share/nginx/html/status.json && sleep 5; done & echo '<!DOCTYPE html><html><body><pre id="data">Loading...</pre><script>setInterval(()=>{fetch("/status.json").then(r=>r.json()).then(d=>document.getElementById("data").innerHTML=JSON.stringify(d,null,2))},3000);</script></body></html>' > /usr/share/nginx/html/index.html && nginx -g daemon off;
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-backend
  ports:
  - port: 8080
    targetPort: 8080
