apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-frontend
  template:
    metadata:
      labels:
        app: monitoring-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh","-c"]
        args:
        - apk add --no-cache curl && echo '<!DOCTYPE html><html><head><title>NKP Monitoring</title><meta http-equiv="refresh" content="10"><style>body{font-family:Arial;background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:40px;text-align:center;}</style></head><body><h1>🚀 NKP-CICD Live Monitoring</h1><div id="data">Loading cluster status...</div><script>fetch("http://monitoring-backend.apps.svc.cluster.local:8080/api/status").then(r=>r.json()).then(d=>document.getElementById("data").innerHTML=`<pre>${JSON.stringify(d,null,2)}</pre>`).catch(()=>document.getElementById("data").innerHTML="Backend not ready");</script></body></html>' > /usr/share/nginx/html/index.html && nginx -g daemon off;
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-frontend
  ports:
  - port: 80
    targetPort: 80

