apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-frontend
  template:
    metadata:
      labels:
        app: monitoring-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args: ["-c", "apk add --no-cache curl && cat > /usr/share/nginx/html/index.html << HTML && nginx -g 'daemon off;'"]
        volumeMounts: []
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-frontend
  ports:
  - port: 80
    targetPort: 80
