apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-frontend
  template:
    metadata:
      labels:
        app: monitoring-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        command:
        - sh
        - -c
        - |
          apk add --no-cache curl &&
          cat > /usr/share/nginx/html/index.html << 'HTML'
<!DOCTYPE html>
<html>
<head><title>NKP Monitoring</title>
<meta http-equiv="refresh" content="10">
<style>body{font-family:Arial;background:linear-gradient(135deg,#667eea,#764ba2);color:white;padding:40px;text-align:center;}
h1{font-size:2.5em;margin-bottom:20px;}
.card{background:rgba(255,255,255,0.1);padding:25px;margin:20px;border-radius:20px;max-width:800px;margin:0 auto;}
pre{background:rgba(0,0,0,0.3);padding:20px;border-radius:10px;text-align:left;font-size:14px;max-height:400px;overflow:auto;}
</style></head>
<body>
<h1>🚀 NKP-CICD Live Monitoring</h1>
<div class="card">
<h2>Cluster Status (auto-refresh 10s)</h2>
<pre id="data">Loading...</pre>
</div>
<script>
async function loadData(){try{
  const r=await fetch('http://monitoring-backend.apps.svc.cluster.local:8080/status.json');
  const d=await r.json();
  document.getElementById('data').textContent=JSON.stringify(d,null,2);
}catch(e){
  document.getElementById('data').textContent='Backend not ready - check monitoring-backend pod logs';
}}
loadData();setInterval(loadData,10000);
</script>
</body>
</html>
HTML
          nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-frontend
  ports:
  - port: 80
    targetPort: 80
