apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-frontend
  template:
    metadata:
      labels:
        app: monitoring-frontend
    spec:
      containers:
      - name: frontend
        image: monitoring-frontend:latest   # build: docker build -t monitoring-frontend:latest ./monitoring-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend
  namespace: apps
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-frontend
  ports:
  - port: 80
    targetPort: 80
